### ISSUE TITLE
[meta] V2.0 - Basic Editing

### ISSUE THREAD

**Issue by RoboPhred** [RoboPhred/oni-duplicity#15]
Version 2.0 intends to provide unguided loading / editing / saving to the parsed save object.

The goal of this version is to get the editor to a basic functional state: The user should be able to edit any non-blob field in the save file object.

No guided editing will be available in this version.  While any field should be editable, the editor will not understand the meaning of any field, and will not provide the user with information regarding the field nor with providing the possible values or any content validation.  It will be up to the user to understand the field and have knowledge of what values it accepts, or risk crashing the game by producing invalid saves.

Validation for primitive types should be provided; it should not be possible for the user to enter values that will result in oni-save-parser failing to write the save data.

Guided editing and content validation will be provided in a future update.

Issues:
- [x] #13 Load and Save
- [ ] #12 Data Editor
- [x] #11 Save Structure Display
- [ ] #16 Export and Import data
- [x] #10 Hosting V2 on gh-pages
- [ ] #4 Translation support

**Comment by RoboPhred** [comment]
Closing - Using project instead of meta-issue
